[project]
name = "concrete-interaction-test"
version = "0.1.0"
description = "Testing a ConCReTE interaction"
requires-python = ">=3.11"
dependencies = [
    "marimo>=0.11.2",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
]
